@Host = http://localhost:7373
@P1 = C:\\\\TEST\\\\A
@P2 = C:\\\\TEST\\\\B

GET {{Host}}/api/monitors
Accept: application/json

###

PUT {{Host}}/api/monitors
Content-Type: application/json

{
  "M": [
    {
      "P": "{{P1}}",
      "M": [  
        {
          "M": 1,
          "E": true,
          "R": false
        }
      ]
    },
    {
      "P": "{{P2}}",
      "M": [
        {
          "M": 1,
          "E": true,
          "R": true
        }
      ]
    }
  ]
}

###

PUT {{Host}}/api/monitors
Content-Type: application/json

{
  "M": []
}
